<?php require('template/header.phtml') ?>

<div class="col-lg-offset-0" id="indexWrapper">

    <h3 id="best-selling-books">Best-Selling Of The Year</h3>
    <hr>

    <div id="myCarousel1" class="carousel slide" data-ride="carousel">


        <!-- Wrapper for slides -->

        <div class="carousel-inner" role="listbox">


            <div class="item active">
                <a href="bookPage.php?id=7"><img src="images/DaVinciCode.jpg" alt="Image"></a>
            </div>

            <div class="item">
                <a href="bookPage.php?id=6"><img src="images/1984.jpeg" alt="Image"></a>
            </div>

        </div>

        <!-- Left and right controls -->
        <a id="left-carousel-control" class="left carousel-control" href="#myCarousel1" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a id="right-carousel-control" class="right carousel-control" href="#myCarousel1" role="button"
           data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>

        <!-- Carousel changing item image by his own -->
        <script>
            $(document).ready(function () {
                // Activate Carousel
                $("#myCarousel").carousel();

                // Enable Carousel Indicators
                $(".item1").click(function () {
                    $("#myCarousel1").carousel(0);
                });
                $(".item2").click(function () {
                    $("#myCarousel1").carousel(1);
                });

                // Enable Carousel Controls
                $(".left").click(function () {
                    $("#myCarousel1").carousel("prev");
                });
                $(".right").click(function () {
                    $("#myCarousel1").carousel("next");
                });
            });
        </script>
    </div>


    <hr>
    <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;New Released</h3>
    <hr>

    <div id="myCarousel2" class="carousel slide" data-ride="carousel">


        <!-- Wrapper for slides -->

        <div class="carousel-inner" role="listbox">


            <div class="item active">
                <a href="bookPage.php?id=5"><img src="images/animalfarm.jpeg" alt="Image"></a>
            </div>

            <div class="item">
                <a href="bookPage.php?id=4"><img src="images/harry-potter.jpg" alt="Image"></a>
            </div>

            <div class="item">
                <a href="bookPage.php?id=1"><img src="images/the-girl-on-the-train.jpg" alt="Image"></a>
            </div>

        </div>

        <!-- Left and right controls -->
        <a id="left-carousel-control" class="left carousel-control" href="#myCarousel2" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a id="right-carousel-control" class="right carousel-control" href="#myCarousel2" role="button"
           data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>

        <!-- Carousel changing item image by his own -->
        <script>
            $(document).ready(function () {
                // Activate Carousel
                $("#myCarousel2").carousel();

                // Enable Carousel Indicators
                $(".item1").click(function () {
                    $("#myCarousel2").carousel(0);
                });
                $(".item2").click(function () {
                    $("#myCarousel2").carousel(1);
                });
                $(".item3").click(function () {
                    $("#myCarousel2").carousel(2);
                });

                // Enable Carousel Controls
                $(".left").click(function () {
                    $("#myCarousel2").carousel("prev");
                });
                $(".right").click(function () {
                    $("#myCarousel2").carousel("next");
                });
            });
        </script>
    </div>

    <hr>
    <h3>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Sales Books</h3>
    <hr>

    <div id="myCarousel3" class="carousel slide" data-ride="carousel">


        <!-- Wrapper for slides -->

        <div class="carousel-inner" role="listbox">


            <div class="item active">
                <a href="bookPage.php?id=8"><img src="images/angles&demos.jpg" alt="Image"></a>
            </div>

            <div class="item">
                <a href="bookPage.php?id=2"><img src="images/And-Then-There-Were-None.JPG" alt="Image"></a>
            </div>

        </div>

        <!-- Left and right controls -->
        <a id="left-carousel-control" class="left carousel-control" href="#myCarousel3" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a id="right-carousel-control" class="right carousel-control" href="#myCarousel3" role="button"
           data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>

        <!-- Carousel changing item image by his own -->
        <script>
            $(document).ready(function () {
                // Activate Carousel
                $("#myCarousel3").carousel();

                // Enable Carousel Indicators
                $(".item1").click(function () {
                    $("#myCarousel3").carousel(0);
                });
                $(".item2").click(function () {
                    $("#myCarousel3").carousel(1);
                });


                // Enable Carousel Controls
                $(".left").click(function () {
                    $("#myCarousel3").carousel("prev");
                });
                $(".right").click(function () {
                    $("#myCarousel3").carousel("next");
                });
            });
        </script>
    </div>

</div>


<?php require('template/footer.phtml') ?>
