<?php require('template/header.phtml') ?>
    <form method="post" name="resetPassForm" role="form" action="../resetPassword.php">
        <div class="col-lg-offset-4" id="loginWrapper">
            <div>
                <h2>Password Reset</h2>
                <hr>
                <img src="../images/resetPass.png" alt="ResetPass-Logo"/></a>
            </div>
            <div id="login2edWrpper">
                <div id="e-mail">
                    <h4>E-mail</h4>
                    <input type="email" name="resetEmail" placeholder="Example@example.com" id="logintxtbox"
                           required/>
                </div>
                <div id="e-mail">
                    <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;New Password</h4>
                    <input type="password" name="resetPassword" placeholder="Example1234" id="logintxtbox"
                           required/>
                </div>
                <div id="password">
                    <h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Confirm
                        Password</h4>
                    <input type="password" name="resetConPassword" placeholder="Example1234" id="logintxtbox"
                           required/><br/>

                    <button type="submit" value="submit" name="resetSubmitBtn" id="LoginBtn">Submit</button>
                </div>
    </form>

<?php require('template/footer.phtml') ?>